"""CLI command to display active top-level OSHA categories from run_pipeline."""

import argparse
import sys
from app.database import SessionLocal
from app.models import Report, Cluster, RiskScore


def main():
    parser = argparse.ArgumentParser(
        description="Display top-level OSHA categories generated by run_pipeline",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python -m app.cli.show_categories
        """
    )
    args = parser.parse_args()

    db = SessionLocal()
    try:
        total_reports = db.query(Report).count()
        if total_reports == 0:
            print("\nNo active dataset found in the database.")
            print("Please run 'python -m app.cli.run_pipeline' first.\n")
            sys.exit(1)

        clusters = db.query(Cluster).filter(Cluster.cluster_num != -1).order_by(Cluster.report_count.desc()).all()
        if not clusters:
            print("\nNo categories discovered in active dataset.\n")
            sys.exit(0)

        print("\n" + "=" * 60)
        print("OSHA PIPELINE TOP-LEVEL CATEGORIES")
        print("=" * 60)
        print(f"Dataset Scope: {total_reports:,} records")
        print(f"Active Categories: {len(clusters)}")
        print("=" * 60 + "\n")

        for idx, c in enumerate(clusters, start=1):
            risk_val = c.risk_score.risk_score if c.risk_score else 0.0
            pct = c.percentage if c.percentage is not None else round((c.report_count / total_reports) * 100.0, 1)
            print(f"{idx:2d}. {c.label}")
            print(f"    Reports: {c.report_count:,} ({pct:.1f}%)")
            print(f"    Dominant Event: {c.dominant_event or 'N/A'}")
            print(f"    Risk Score: {risk_val:.1f}\n")

        print("=" * 60)
        print("To drill down into a category, run:")
        print("  python -m app.cli.enter_category --category <name>")
        print("=" * 60 + "\n")

    except Exception as e:
        print(f"\n✗ Error retrieving categories: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    finally:
        db.close()


if __name__ == "__main__":
    main()
